(function(g){var window=this;var ssa=function(a,b){return g.Vb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},$5=function(a,b,c){g.Ia(c)||(c=[String(c)]);
g.Sm(a.w,b,c)},tsa=function(a,b){var c=[];
g.mk(b,function(d){try{var e=g.Hn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Gn(e)&&c.push(d)},a);
return c},usa=function(a,b){var c=tsa(a,b);
(0,g.z)(c,function(d){g.Hn.prototype.remove.call(this,d)},a)},vsa=function(a){if(a.kd){if(a.kd.locationOverrideToken)return{locationOverrideToken:a.kd.locationOverrideToken};
if(null!=a.kd.latitudeE7&&null!=a.kd.longitudeE7)return{latitudeE7:a.kd.latitudeE7,longitudeE7:a.kd.longitudeE7}}return null},wsa=function(a,b){g.Za(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},xsa=function(a,b){var c=b instanceof g.zc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},b6=function(){},ysa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},zsa=function(a){if(a.pd&&"function"==typeof a.pd)return a.pd();
if("string"===typeof a)return a.split("");if(g.Ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Asa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ja(a)||"string"===typeof a)(0,g.z)(a,b,void 0);else{if(a.ie&&"function"==typeof a.ie)var c=a.ie();else if(a.pd&&"function"==typeof a.pd)c=void 0;else if(g.Ja(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=zsa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Bsa=function(a,b,c,d){var e=new g.Gm(null,void 0);
a&&g.Hm(e,a);b&&g.Im(e,b);c&&g.Jm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Qo[a]=!0;
var c=g.Oo();c&&c.publish.apply(c,arguments);g.Qo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Dm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Csa(this,a.capabilities||""),Dsa(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Csa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Oa(ssa,Esa)).forEach(function(c){a.capabilities.add(c)})},Dsa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Fsa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Gsa=function(a){return new e6(a)},Hsa=function(a){return g.Ia(a)?(0,g.Ic)(a,Gsa):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ia(a)?"["+(0,g.Ic)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Isa=function(a){return(0,g.Ic)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Va(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Va(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Cs)(),c=(0,g.Bs)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Jsa=function(){var a=(0,g.Bs)();
a&&usa(a,a.o.xf(!0))},m6=function(){var a=g.Es("yt-remote-connected-devices")||[];
g.qb(a);return a},Ksa=function(a){if(g.$a(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Lsa=function(a){g.Ds("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Es("yt-remote-device-id");a||(a=i6(),g.Ds("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Za(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.Za(a,b);g.Fs()&&g.sb(a,b);a=Ksa(a);if(g.$a(a))try{g.qr("remote_sid")}catch(c){}else try{g.pr("remote_sid",a.join(","),-1)}catch(c){}},Msa=function(){return g.Es("yt-remote-session-browser-channel")},Nsa=function(){return g.Es("yt-remote-local-screens")||[]},Osa=function(){g.Ds("yt-remote-lounge-token-expiration",!0,86400)},Psa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ic)(Nsa(),function(d){return d.loungeToken}),c=(0,g.Ic)(a,function(d){return d.loungeToken});
(0,g.si)(c,function(d){return!g.Za(b,d)})&&Osa();
g.Ds("yt-remote-local-screens",a,31536E3)},Qsa=function(a,b){g.Ds("yt-remote-session-browser-channel",a);
g.Ds("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.Za(c,d)||c.push(d);Lsa(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.cb(a,o6());Lsa(a)},Rsa=function(){if(!r6){var a=g.Rn();
a&&(r6=new g.Bn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Ssa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Tsa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Usa(a.shift(),function(){s6(a)}):t6()},Vsa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Usa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Tsa();
a&&a(!1,"No cast extension found")},Xsa=function(){if(Wsa){var a=2,b=Tsa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Usa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Ysa=function(){Xsa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.cd=b;this.B=(0,g.x)(this.lE,this);this.o=!1;this.u=0;this.w=this.Ha=null;this.A=[]},v6=function(a,b,c){g.A.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.cd=b;this.u=(0,g.x)(this.mE,this);this.o=[]},w6=function(a){a.Ha=g.yf(a.u,a.cd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return ysa(a)},y6=function(){},z6=function(){},Zsa=function(){},ata=function(a){return(a=$sa(a))?new ActiveXObject(a):new XMLHttpRequest},$sa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.q1(this);this.u=new g.xf;this.u.setInterval(250)},cta=function(a,b,c){a.yi=1;
a.lg=Z5(b.clone());a.Oh=c;a.C=!0;bta(a,null)},B6=function(a,b,c,d,e){a.yi=1;
a.lg=Z5(b.clone());a.Oh=null;a.C=c;e&&(a.RA=!1);bta(a,d)},bta=function(a,b){a.jj=(0,g.H)();
C6(a);a.Rg=a.lg.clone();$5(a.Rg,"t",a.F);a.El=0;a.Bc=a.o.Vp(a.o.sl()?b:null);0<a.Fq&&(a.no=new v6((0,g.x)(a.WB,a,a.Bc),a.Fq));a.A.ga(a.Bc,"readystatechange",a.qN);var c=a.rh?g.ac(a.rh):{};a.Oh?(a.Qo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Bc.send(a.Rg,a.Qo,a.Oh,c)):(a.Qo="GET",a.RA&&!g.Nd&&(c.Connection="close"),a.Bc.send(a.Rg,a.Qo,null,c));a.o.Ge(1)},fta=function(a,b,c){for(var d=!0;!a.dh&&a.El<c.length;){var e=dta(a,c);
if(e==D6){4==b&&(a.xg=4,E6(15),d=!1);break}else if(e==eta){a.xg=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.xg=1,E6(17),d=!1);a.He=a.He&&d;d||(G6(a),H6(a))},dta=function(a,b){var c=a.El,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return eta;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.El=d+c;return e},hta=function(a,b){a.jj=(0,g.H)();
C6(a);var c=b?window.location.hostname:"";a.Rg=a.lg.clone();Y5(a.Rg,"DOMAIN",c);Y5(a.Rg,"t",a.F);try{a.Le=new ActiveXObject("htmlfile")}catch(n){G6(a);a.xg=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in gta)k=I6[l]=gta[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Vc(g.qc("b/12014412"),d+"</body></html>");a.Le.open();a.Le.write(g.Qc(c));a.Le.close();a.Le.parentWindow.m=(0,g.x)(a.IM,a);a.Le.parentWindow.d=(0,g.x)(a.aA,a,!0);a.Le.parentWindow.rpcClose=(0,g.x)(a.aA,a,!1);c=a.Le.createElement("DIV");a.Le.parentWindow.document.body.appendChild(c);d=g.Cc(a.Rg.toString());d=g.bd(g.Ac(d));d=g.Vc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Wc(c,d);a.o.Ge(1)},C6=function(a){a.Yt=(0,g.H)()+a.B;
ita(a,a.B)},ita=function(a,b){if(null!=a.wj)throw Error("WatchDog timer not null");
a.wj=J6((0,g.x)(a.QM,a),b)},K6=function(a){a.wj&&(g.v.clearTimeout(a.wj),a.wj=null)},H6=function(a){a.o.Kw()||a.dh||a.o.co(a)},G6=function(a){K6(a);
g.je(a.no);a.no=null;a.u.stop();g.s1(a.A);if(a.Bc){var b=a.Bc;a.Bc=null;b.abort();b.dispose()}a.Le&&(a.Le=null)},F6=function(a,b){try{a.o.Uz(a,b),a.o.Ge(4)}catch(c){}},kta=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;jta(a,b,function(k){k?c(!0):g.v.setTimeout(function(){kta(a,b,c,d,f)},f)})}},jta=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
xsa(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},lta=function(a){this.o=a;
this.u=new y6},mta=function(a){var b=M6(a.o,a.Ij,"/mail/images/cleardot.gif");
Z5(b);kta(b.toString(),5E3,(0,g.x)(a.hD,a),3,2E3);a.Ge(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Dd=new A6(a,void 0,void 0,void 0),a.Dd.rh=a.Dq,b=a.o,b=M6(b,b.sl()?a.fk:null,a.Eq),E6(5),!g.Ld||g.pd(10))$5(b,"TYPE","xmlhttp"),B6(a.Dd,b,!1,a.fk,!1);else{$5(b,"TYPE","html");var c=a.Dd;a=!!a.fk;c.yi=3;c.lg=Z5(b.clone());hta(c,a)}},P6=function(a){g.Je.call(this);
this.headers=new g.Dm;this.T=a||null;this.w=!1;this.O=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.Z=this.G=this.U=!1;this.F=0;this.M=null;this.na="";this.J=this.Y=!1},nta=function(a){return g.Ld&&g.od(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},ota=function(a){return"content-type"==a.toLowerCase()},qta=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;pta(a);Q6(a)},pta=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},sta=function(a){if(a.w&&"undefined"!=typeof g.y1)if(a.O[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.yf(a.Mw,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!rta.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";pta(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){tta(a);
var c=a.o,d=a.O[0]?g.Fa:null;a.o=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},tta=function(a){a.o&&a.J&&(a.o.ontimeout=null);
a.M&&(g.v.clearTimeout(a.M),a.M=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},uta=function(a,b){this.o=a;
this.map=b;this.context=null},vta=function(a){g.le.call(this,"statevent",a)},wta=function(a,b){g.le.call(this,"timingevent",a);
this.size=b},xta=function(a){g.le.call(this,"serverreachability",a)},Ata=function(a){yta(a);
if(3==a.o){var b=a.Rk++,c=a.Hm.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.yi=2;b.lg=Z5(c.clone());xsa(new Image,b.lg.toString());b.jj=(0,g.H)();C6(b)}zta(a)},Bta=function(a){a.ED(1,0);
a.Hm=M6(a,null,a.Cq);W6(a)},yta=function(a){a.qg&&(a.qg.abort(),a.qg=null);
a.Wb&&(a.Wb.cancel(),a.Wb=null);a.Af&&(g.v.clearTimeout(a.Af),a.Af=null);X6(a);a.wd&&(a.wd.cancel(),a.wd=null);a.ug&&(g.v.clearTimeout(a.ug),a.ug=null)},Cta=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new uta(a.cJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.wd||a.ug||(a.ug=J6((0,g.x)(a.Zz,a),0),a.oi=0)},Eta=function(a,b){if(1==a.o){if(!b){a.Rk=Math.floor(1E5*Math.random());
var c=a.Rk++,d=new A6(a,"",c,void 0);d.rh=null;var e=Y6(a),f=a.Hm.clone();Y5(f,"RID",c);Y5(f,"CVER","1");V6(a,f);cta(d,f,e);a.wd=d;a.o=2}}else 3==a.o&&(b?Dta(a,b):0==a.u.length||a.wd||Dta(a))},Dta=function(a,b){if(b)if(6<a.eh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Rk-1;var d=Y6(a)}else c=b.G,d=b.Oh;else c=a.Rk++,d=Y6(a);var e=a.Hm.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.Mi);V6(a,e);c=new A6(a,a.w,c,a.oi+1);c.rh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.wd=c;cta(c,e,d)},V6=function(a,b){if(a.Yc){var c=a.Yc.hw();
c&&g.Lb(c,function(d,e){Y5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.eh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.eh?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Fta=function(a){a.Wb||a.Af||(a.F=1,a.Af=J6((0,g.x)(a.Yz,a),0),a.ii=0)},Z6=function(a){if(a.Wb||a.Af||3<=a.ii)return!1;
a.F++;a.Af=J6((0,g.x)(a.Yz,a),Gta(a,a.ii));a.ii++;return!0},N6=function(a,b,c){a.Oo=c;
a.Te=b.Nf;a.C||Bta(a)},X6=function(a){null!=a.hh&&(g.v.clearTimeout(a.hh),a.hh=null)},Gta=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Yc&&(c=null);var d=(0,g.x)(a.YN,a);c||(c=new g.Gm("//www.google.com/images/cleardot.gif"),Z5(c));jta(c.toString(),1E4,d)}else E6(2);Hta(a,b)},Hta=function(a,b){a.o=0;
a.Yc&&a.Yc.yv(b);zta(a);yta(a)},zta=function(a){a.o=0;
a.Te=-1;if(a.Yc)if(0==a.A.length&&0==a.u.length)a.Yc.Np();else{g.gb(a.A);var b=g.gb(a.u);a.A.length=0;a.u.length=0;a.Yc.Np(b)}},M6=function(a,b,c){var d=g.Om(c);
if(""!=d.o)b&&g.Im(d,b+"."+d.o),g.Jm(d,d.B);else{var e=window.location;d=Bsa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Uj&&g.Lb(a.Uj,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.eh);V6(a,d);return d},J6=function(a,b){if(!g.Ka(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new vta(a7,a))},Ita=function(){},Jta=function(){this.o=[];
this.u=[]},Kta=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.J(this.zM,0,this);g.C(this,this.o);this.cd=5E3;this.u=0;if(g.Ka(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ka(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.M=a;
this.C=b;this.w=new g.An;this.u=new b7(this.DN,this);this.o=null;this.qb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.J=c||!1},Lta=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Oo,sessionId:a.o.w,arrayId:a.o.Mi}},Mta=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Eta(a.o),Ata(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Nta=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.bh(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.A,d,!0),onError:g.Oa(a.w,e),Zd:g.Oa(a.B,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Lp(b,a)},Rta=function(){var a=Ota;
Pta();h7.push(a);Qta(h7)},i7=function(a,b){Pta();
var c=h7,d=Sta(a,String(b));g.$a(c)?Tta(d):(Qta(c),(0,g.z)(c,function(e){e(d)}))},Pta=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",h7,void 0))},Tta=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Qta=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Sta=function(a,b){var c=((0,g.H)()-Uta)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},Vta=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Wta=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Yd)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Vta(a,b[d])||c;return c},Xta=function(a,b){var c=a.o.length;
a.o=(0,g.Yd)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.B=b;this.w=c;this.A=d;this.u=0;this.o=null;this.Ha=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},Yta=function(a){if(a.o.length){var b=(0,g.Ic)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.vE,a),(0,g.x)(a.uE,a))}},o7=function(a){var b=Hsa(Nsa());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Wta(a,b)},q7=function(a,b){Psa((0,g.Ic)(a.o,Fsa));
b&&Osa()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.Es("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Za(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Nk(this.o))},Zta=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Nk(a.o)),a.o=b,a.R("screenChange"));$ta(a)},u7=function(a){isNaN(a.w)||g.No(a.w);
a.w=g.Lo((0,g.x)(a.it,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},aua=function(a){var b={};
(0,g.z)(a.C(),function(c){c.token?b[c.token]=c.id:this.Ob("Requesting availability of screen w/o lounge token.")});
return b},$ta=function(a){a=g.Sb(g.Mb(a.o,function(b){return b}));
g.qb(a);a.length?g.Ds("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};bua(this)},dua=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Td();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);Zta(a.u,l,function(m){e(m?l:null)})}else c?cua(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Zta(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},eua=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},cua=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Lp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},fua=function(a){a.o=a.w.Td();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},bua=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.DE,a));fua(a);a.A=Hsa(g.Es("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.Td,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ds("yt-remote-automatic-screen-cache",(0,g.Ic)(a.A,Fsa)));x7(a);a.B[b.uuid]=b.id;g.Ds("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Es("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.O=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.O,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.IO,this);this.B=(0,g.x)(this.ZM,this);this.A=g.Lo((0,g.x)(function(){gua(this,null)},this),12E4)},hua=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Nk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Fa,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Nk(b))},gua=function(a,b){g.No(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.fo,a),d=(0,g.x)(a.Yd,a);a.Cw(b,c,d,5)}}else a.Yd(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.M="";this.T=c;this.B=null;this.F=g.Fa;this.C=NaN;this.J=(0,g.x)(this.LO,this);this.o=g.Fa},iua=function(a){a.o=a.H.cC(a.M,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Fa;
this.fo(b)},a),(0,g.x)(function(b){this.o=g.Fa;
this.Yd(b)},a))},jua=function(a){var b={};
b.pairingCode=a.M;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Rsa()&&(b.env_useStageMdx=1);return g.$g(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Lo((0,g.x)(this.Ni,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.JL,this)},kua=function(a,b){return b?g.Va(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Ota=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.je(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.Xz,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.Ni(null)):a.R("yt-remote-cast2-session-change",null))},lua=function(a){var b=a.u.bC(),c=a.o&&a.o.u;
a=(0,g.Ic)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=kua(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},rua=function(a,b,c,d,e,f,k){mua()?nua(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?oua(a,c):(window.__onGCastApiAvailable=function(l,m){l?oua(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),pua(),c(!1))},d?g.Yo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Ysa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(Xsa(),s6(qua.map(Vsa))))):H7("Cannot initialize because not running Chrome")},pua=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);sua(!1);g.To(M7);M7.length=0},N7=function(){return!!g.Es("yt-remote-cast-installed")},tua=function(){var a=g.Es("yt-remote-cast-receiver");
return a?a.friendlyName:null},uua=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},vua=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.So("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},mua=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Rv||a},wua=function(a,b){L7().init(a,b)},nua=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ds("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Ds("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Ds("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},oua=function(a,b){K7(!0);
I7(!1);wua(a,function(c){c?(sua(!0),g.Vo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),pua());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Ds("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},sua=function(a){H7("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.Ue=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Ue=!1;a.hasNext=!1;a.F=0;a.C=(0,g.H)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.H)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.H)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.o);b.hasPrevious=a.Ue;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Jta;this.w=this.u=null;this.H=(0,g.x)(this.KJ,this);this.F=(0,g.x)(this.Uk,this);this.G=(0,g.x)(this.JJ,this);this.M=(0,g.x)(this.WJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.cu,this),xua(this))):c=3;0!=c&&(b?this.cu(c):g.Lo((0,g.x)(function(){this.cu(c)},this),0));
var d=vua();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.M)},$7=function(a){return new R7(a.A.getPlayerContextData())},xua=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Oa(this.GL,b),this))},a)},yua=function(a){(0,g.z)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){yua(a);
a.A.setPlayerContextData(X7(b));xua(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.Uk(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.Uk(a.w.media[0]))},zua=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Ob("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Ob("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.J=!1;this.G=this.F=this.H=this.M=NaN;this.O=[];this.A=this.C=this.w=this.Sa=this.o=null;this.U=a;this.O.push(g.Tq(window,"beforeunload",(0,g.x)(this.oE,this)));this.u=[];this.Sa=new R7;this.T=b.id;this.o=Aua(this,c);this.o.subscribe("handlerOpened",this.OJ,this);this.o.subscribe("handlerClosed",this.LJ,this);this.o.subscribe("handlerError",this.MJ,this);this.o.subscribe("handlerMessage",this.NJ,this);Nta(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Sa.videoId;
g.Fs()&&g.Ds("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Aua=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},Bua=function(a){a.B=g.Lo((0,g.x)(function(){g8("Connecting timeout");
this.ni(1)},a),2E4)},i8=function(a){g.No(a.B);
a.B=NaN},j8=function(a){g.No(a.M);
a.M=NaN},Cua=function(a){k8(a);
a.H=g.Lo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.No(a.H);
a.H=NaN},Eua=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Aw()&&a.Sa.reset(),h8(a,1),l8(a,"getNowPlaying"),Dua(a)):a.ni(1)},Fua=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.Yb(b.params)?a.Sa.o=null:a.Sa.o=b.params,a.R("remotePlayerChange"))},Gua=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;W7(a.Sa,c,d);a.R("remoteQueueChange")},Iua=function(a,b){b.params=b.params||{};
Gua(a,b);Hua(a,b);a.R("autoplayDismissed")},Hua=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Sa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Sa.G=isNaN(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Sa.playerState?Cua(a):k8(a);a.R("remotePlayerChange")},Jua=function(a,b){if(-1E3!=
a.Sa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Sa,isNaN(c)?0:c);a.R("remotePlayerChange")}},Kua=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=parseInt(b.params.volume,10);a.Sa.muted=c;a.R("remotePlayerChange")},Lua=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},Mua=function(a,b){var c="true"==b.params.hasNext;
a.Sa.Ue="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.R("previousNextChange")},Dua=function(a){g.No(a.G);
a.G=g.Lo((0,g.x)(a.ni,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Nk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.bd=a;this.u=[];this.u.push(this.bd.$_s("screenChange",(0,g.x)(this.GO,this)));this.u.push(this.bd.$_s("onlineScreenChange",(0,g.x)(this.lL,this)))},Rua=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.N("MDX_CONFIG")||b;Jsa();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Rsa()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",o8,void 0));Nua();var c=p8();if(!c){var d=new v7(n8);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);rua(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Nk(b)),s8.push(g.So("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.So("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.So("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.So("yt-remote-cast2-session-change",Oua)),s8.push(g.So("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),uua())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Cp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Nk(a)),Pua(a),c.start(),q8()||Qua())},Tua=function(){var a=Sua();
N7()&&g.Es("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Sua=function(){var a=p8().bd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Isa(a)},y8=function(){var a=Uua();
!a&&N7()&&tua()&&(a={key:"cast-selector-receiver",name:tua()});return a},Uua=function(){var a=Sua(),b=w8();
b||(b=u8());return g.Va(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().Td();return k6(b,a)},Oua=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Vua=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},Wua=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Vua("");g.Ea("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.z)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.Fs();
if(!a)return null;var b=p8().Td();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Vua(a.id);var c=new f8(n8,a,v8());c.connect(b,Wua());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Qua=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),uua(),r8("Skipping connecting because no session screen found."))},Nua=function(){var a=v8();
if(g.Yb(a)){a=o6();var b=g.Es("yt-remote-session-name")||"",c=g.Es("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Pua=function(a){a?(g.Ds("yt-remote-session-app",a.app),g.Ds("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.C(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.HK);this.w.L(b,"captionschanged",this.IJ);this.w.L(b,"captionssettingschanged",this.mB);this.w.L(b,"videoplayerreset",this.ho);this.w.L(b,"mdxautoplaycancel",this.gD);this.T=this.w.L(b,"onVolumeChange",this.Fz);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.Tz,this);c.subscribe("remotePlayerChange",this.Xk,this);c.subscribe("remoteQueueChange",this.ho,this);c.subscribe("autoplayUpNext",this.vz,
this);c.subscribe("previousNextChange",this.Qz,this);c.subscribe("nowAutoplaying",this.Mz,this);c.subscribe("autoplayDismissed",this.uz,this);this.suggestion=null;this.H=new g.wD(64);this.A=new g.J(this.iB,500,this);g.C(this,this.A);this.C=new g.J(this.jB,1E3,this);g.C(this,this.C);this.J=new u6(this.iO,0,this);g.C(this,this.J);this.F={};this.O=new g.J(this.OB,1E3,this);g.C(this,this.O);this.M=new v6(this.jH,1E3,this);g.C(this,this.M);this.U=g.Fa;this.mB();this.ho();this.Xk()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.O=b||0;c.player.R("progresssync",b,d)},Xua=function(a){H8(a,0);
a.A.stop();I8(a,new g.wD(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.dc(c,b));a.o.XA(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Ua;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.We,vsa(c));I8(a,new g.wD(1))},Yua=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{DS:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.CD(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.OS(a.u.app,d);a.H=b;Zua(a.B,c,b)}},M8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",N:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",V:"\u0412\u044b \u0432\u044b\u0448\u043b\u0438 \u0438\u0437 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430"},{D:"div",I:"ytp-mdx-popup-description",V:'\u0420\u043e\u043b\u0438\u043a\u0438, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0432\u044b \u043f\u043e\u0441\u043c\u043e\u0442\u0440\u0438\u0442\u0435, \u043c\u043e\u0433\u0443\u0442 \u0431\u044b\u0442\u044c \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u044b \u0432 \u0438\u0441\u0442\u043e\u0440\u0438\u044e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430 \u043d\u0430 \u0442\u0435\u043b\u0435\u0432\u0438\u0437\u043e\u0440\u0435, \u0447\u0442\u043e \u0441\u043a\u0430\u0436\u0435\u0442\u0441\u044f \u043d\u0430 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f\u0445. \u0427\u0442\u043e\u0431\u044b \u044d\u0442\u043e\u0433\u043e \u0438\u0437\u0431\u0435\u0436\u0430\u0442\u044c, \u0432\u044b\u0431\u0435\u0440\u0438\u0442\u0435 "\u041e\u0442\u043c\u0435\u043d\u0430" \u0438 \u0432\u043e\u0439\u0434\u0438\u0442\u0435 \u0432 \u0430\u043a\u043a\u0430\u0443\u043d\u0442 \u043d\u0430 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u0435.'},
{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"\u041e\u0442\u043c\u0435\u043d\u0430"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],V:"\u041e\u041a"}]}]}]});this.u=new g.aM(this,250);g.C(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.cM()]},{D:"div",I:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.u=new g.aM(this,250);g.C(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);$ua(this,g.pL(a))},$ua=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.HM('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.DD(b)||g.W(b,4)?g.HM('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.HM('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.ha("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.qO.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.zP.call(this,a);
this.u={key:i6(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.B=null;this.A=[];this.T=this.o=null;this.M=[this.u];this.w=this.u;this.F=new g.wD(64);this.O=0;this.H=-1;this.C=null;if(!g.Tx(this.player.P())){a=this.player;var b=g.cD(a);b&&(b=b.Jk())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.HL(a,b.element,4);this.C=new M8;g.C(this,this.C);g.HL(a,this.C.element,4);this.J=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",
a.G),a.G=null)},Zua=function(a,b,c){a.F=c;
a.player.R("presentingplayerstatechange",new g.ID(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.P().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.N("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.N("SESSION_INDEX")&&!g.N("LOGGED_IN")))||a.J||!a.C);if(c?0:a.player.P().uh()||"WEB_EMBEDDED_PLAYER"==a.player.P().deviceParams.c)g.DD(g.pL(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.eN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.u.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2==a.player.app.U||1==a.player.app.U)&&g.R(a.player.P().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.xa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.We,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=vsa(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Nk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().Td(),(c=k6(c,b.key))&&A8(c,1))}},gta={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},ava={},Esa={jP:"atp",NR:"ska",CR:"que",WQ:"mus",MR:"sus",iQ:"dsp",JR:"seq"};
d6.prototype.rg=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var r6,n6="",Wsa=Ssa("loadCastFramework")||Ssa("loadCastApplicationFramework"),qua=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Qa(u6,g.A);g.h=u6.prototype;g.h.kE=function(a){this.A=arguments;this.o=!1;this.Ha?this.w=(0,g.H)()+this.cd:this.Ha=g.yf(this.B,this.cd)};
g.h.stop=function(){this.Ha&&(g.v.clearTimeout(this.Ha),this.Ha=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Cb.X.call(this)};
g.h.lE=function(){this.w?(this.Ha=g.yf(this.B,this.w-(0,g.H)()),this.w=null):(this.Ha=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Qa(v6,g.A);g.h=v6.prototype;g.h.xi=!1;g.h.ek=0;g.h.Ha=null;g.h.Jw=function(a){this.o=arguments;this.Ha||this.ek?this.xi=!0:w6(this)};
g.h.stop=function(){this.Ha&&(g.v.clearTimeout(this.Ha),this.Ha=null,this.xi=!1,this.o=[])};
g.h.pause=function(){this.ek++};
g.h.resume=function(){this.ek--;this.ek||!this.xi||this.Ha||(this.xi=!1,w6(this))};
g.h.X=function(){v6.Cb.X.call(this);this.stop()};
g.h.mE=function(){this.Ha=null;this.xi&&!this.ek&&(this.xi=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},$sa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Qa(Zsa,z6);S8=new Zsa;g.h=A6.prototype;g.h.rh=null;g.h.He=!1;g.h.wj=null;g.h.Yt=null;g.h.jj=null;g.h.yi=null;g.h.lg=null;g.h.Rg=null;g.h.Oh=null;g.h.Bc=null;g.h.El=0;g.h.Le=null;g.h.Qo=null;g.h.xg=null;g.h.gk=-1;g.h.RA=!0;g.h.dh=!1;g.h.Fq=0;g.h.no=null;var eta={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.qN=function(a){a=a.target;var b=this.no;b&&3==R6(a)?b.Jw():this.WB(a)};
g.h.WB=function(a){try{if(a==this.Bc)a:{var b=R6(this.Bc),c=this.Bc.C,d=this.Bc.getStatus();if(g.Ld&&!g.pd(10)||g.Nd&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.th&&!T6(this.Bc))break a;this.dh||4!=b||7==c||(8==c||0>=d?this.o.Ge(3):this.o.Ge(2));K6(this);var e=this.Bc.getStatus();this.gk=e;var f=T6(this.Bc);(this.He=200==e)?(4==b&&G6(this),this.C?(fta(this,b,f),g.th&&this.He&&3==b&&(this.A.ga(this.u,"tick",this.kN),this.u.start())):F6(this,f),this.He&&!this.dh&&(4==b?this.o.co(this):(this.He=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.xg=3,E6(13)):(this.xg=0,E6(14)),G6(this),H6(this))}}catch(k){this.Bc&&T6(this.Bc)}finally{}};
g.h.kN=function(){var a=R6(this.Bc),b=T6(this.Bc);this.El<b.length&&(K6(this),fta(this,a,b),this.He&&4!=a&&C6(this))};
g.h.IM=function(a){J6((0,g.x)(this.HM,this,a),0)};
g.h.HM=function(a){this.dh||(K6(this),F6(this,a),C6(this))};
g.h.aA=function(a){J6((0,g.x)(this.GM,this,a),0)};
g.h.GM=function(a){this.dh||(G6(this),this.He=a,this.o.co(this),this.o.Ge(4))};
g.h.cancel=function(){this.dh=!0;G6(this)};
g.h.QM=function(){this.wj=null;var a=(0,g.H)();0<=a-this.Yt?(2!=this.yi&&this.o.Ge(3),G6(this),this.xg=2,E6(18),H6(this)):ita(this,this.Yt-a)};
g.h.getLastError=function(){return this.xg};g.h=lta.prototype;g.h.Dq=null;g.h.Dd=null;g.h.oo=!1;g.h.Lw=null;g.h.Fm=null;g.h.rr=null;g.h.Eq=null;g.h.le=null;g.h.Nf=-1;g.h.fk=null;g.h.Ij=null;g.h.connect=function(a){this.Eq=a;a=M6(this.o,null,this.Eq);E6(3);this.Lw=(0,g.H)();var b=this.o.G;null!=b?(this.fk=b[0],(this.Ij=b[1])?(this.le=1,mta(this)):(this.le=2,O6(this))):($5(a,"MODE","init"),this.Dd=new A6(this,void 0,void 0,void 0),this.Dd.rh=this.Dq,B6(this.Dd,a,!1,null,!0),this.le=0)};
g.h.hD=function(a){if(a)this.le=2,O6(this);else{E6(4);var b=this.o;b.Te=b.qg.Nf;$6(b,9)}a&&this.Ge(2)};
g.h.Vp=function(a){return this.o.Vp(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.Nf=-1};
g.h.Kw=function(){return!1};
g.h.Uz=function(a,b){this.Nf=a.gk;if(0==this.le)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.Te=this.Nf;$6(c,2);return}this.fk=c[0];this.Ij=c[1]}else c=this.o,c.Te=this.Nf,$6(c,2);else if(2==this.le)if(this.oo)E6(7),this.rr=(0,g.H)();else if("11111"==b){if(E6(6),this.oo=!0,this.Fm=(0,g.H)(),c=this.Fm-this.Lw,!g.Ld||g.pd(10)||500>c)this.Nf=200,this.Dd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Fm=this.rr=(0,g.H)(),this.oo=!1};
g.h.co=function(){this.Nf=this.Dd.gk;if(this.Dd.He)0==this.le?this.Ij?(this.le=1,mta(this)):(this.le=2,O6(this)):2==this.le&&((!g.Ld||g.pd(10)?!this.oo:200>this.rr-this.Fm)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.le?E6(9):2==this.le&&E6(10);var a=this.o;this.Dd.getLastError();a.Te=this.Nf;$6(a,2)}};
g.h.sl=function(){return this.o.sl()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Ge=function(a){this.o.Ge(a)};g.Qa(P6,g.Je);var rta=/^https?$/i,bva=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.T?ata(this.T):ata(S8);this.O=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.Mw,this);try{b6(S6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));qta(this,f);return}a=c||
"";var e=this.headers.clone();d&&Asa(d,function(f,k){e.set(k,f)});
d=g.Va(e.ie(),ota);c=g.v.FormData&&a instanceof g.v.FormData;!g.Za(bva,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.na&&(this.o.responseType=this.na);"withCredentials"in this.o&&this.o.withCredentials!==this.Y&&(this.o.withCredentials=this.Y);try{tta(this),0<this.F&&(this.J=nta(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.J)),this.J?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Nw,this)):this.M=g.yf(this.Nw,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),qta(this,f)}};
g.h.Nw=function(){"undefined"!=typeof g.y1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Cb.X.call(this)};
g.h.Mw=function(){this.ka()||(this.Z||this.G||this.B?sta(this):this.IL())};
g.h.IL=function(){sta(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Uj=null;g.h.wd=null;g.h.Wb=null;g.h.Cq=null;g.h.Hm=null;g.h.fv=null;g.h.Vm=null;g.h.Rk=0;g.h.cJ=0;g.h.Yc=null;g.h.ug=null;g.h.Af=null;g.h.hh=null;g.h.qg=null;g.h.Oo=null;g.h.Mi=-1;g.h.xx=-1;g.h.Te=-1;g.h.oi=0;g.h.ii=0;g.h.eh=8;var a7=new g.Je;g.Qa(vta,g.le);g.Qa(wta,g.le);g.Qa(xta,g.le);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Cq=b;this.Uj=c||{};d&&void 0!==e&&(this.Uj.OSID=d,this.Uj.OAID=e);this.C?(J6((0,g.x)(this.Ev,this,a),100),Bta(this)):this.Ev(a)};
g.h.Ev=function(a){this.qg=new lta(this);this.qg.Dq=null;this.qg.u=this.B;this.qg.connect(a)};
g.h.Kw=function(){return 0==this.o};
g.h.Zz=function(a){this.ug=null;Eta(this,a)};
g.h.Yz=function(){this.Af=null;this.Wb=new A6(this,this.w,"rpc",this.F);this.Wb.rh=null;this.Wb.Fq=0;var a=this.fv.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.Oo?"0":"1");Y5(a,"AID",this.Mi);V6(this,a);if(!g.Ld||g.pd(10))Y5(a,"TYPE","xmlhttp"),B6(this.Wb,a,!0,this.Vm,!1);else{Y5(a,"TYPE","html");var b=this.Wb,c=!!this.Vm;b.yi=3;b.lg=Z5(a.clone());hta(b,c)}};
g.h.Uz=function(a,b){if(0!=this.o&&(this.Wb==a||this.wd==a))if(this.Te=a.gk,this.wd==a&&3==this.o)if(7<this.eh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ia(c)&&3==c.length)if(0==c[0])a:{if(!this.Af){if(this.Wb)if(this.Wb.jj+3E3<this.wd.jj)X6(this),this.Wb.cancel(),this.Wb=null;else break a;Z6(this);E6(19)}}else this.xx=c[1],0<this.xx-this.Mi&&37500>c[2]&&this.Oo&&0==this.ii&&!this.hh&&(this.hh=J6((0,g.x)(this.EJ,this),6E3));else $6(this,11)}else b!=ava.GP.o&&$6(this,11);else if(this.Wb==a&&
X6(this),!g.xb(b)){c=this.B.parse(b);g.Ia(c);for(var d=0;d<c.length;d++){var e=c[d];this.Mi=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.Vm=e[2],e=e[3],null!=e?this.eh=e:this.eh=6,this.o=3,this.Yc&&this.Yc.Av(),this.fv=M6(this,this.sl()?this.Vm:null,this.Cq),Fta(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Yc&&this.Yc.zv(e),this.ii=0)}}};
g.h.EJ=function(){null!=this.hh&&(this.hh=null,this.Wb.cancel(),this.Wb=null,Z6(this),E6(20))};
g.h.co=function(a){if(this.Wb==a){X6(this);this.Wb=null;var b=2}else if(this.wd==a)this.wd=null,b=1;else return;this.Te=a.gk;if(0!=this.o)if(a.He)1==b?(b=(0,g.H)()-a.jj,a7.dispatchEvent(new wta(a7,a.Oh?a.Oh.length:0,b,this.oi)),W6(this),this.A.length=0):Fta(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Te)){if(d=1==b)this.wd||this.ug||1==this.o||2<=this.oi?d=!1:(this.ug=J6((0,g.x)(this.Zz,this,a),Gta(this,this.oi)),this.oi++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.ED=function(a){if(!g.Za(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.YN=function(a){a?E6(2):(E6(1),Hta(this,8))};
g.h.Vp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Y=!1;return a};
g.h.isActive=function(){return!!this.Yc&&this.Yc.isActive(this)};
g.h.Ge=function(a){a7.dispatchEvent(new xta(a7,a))};
g.h.sl=function(){return!(!g.Ld||g.pd(10))};
g.h=Ita.prototype;g.h.Av=function(){};
g.h.zv=function(){};
g.h.yv=function(){};
g.h.Np=function(){};
g.h.hw=function(){return{}};
g.h.isActive=function(){return!0};g.h=Jta.prototype;g.h.isEmpty=function(){return g.$a(this.o)&&g.$a(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.Za(this.o,a)||g.Za(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Yna)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.u,a)};
g.h.pd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(b7,g.A);g.h=b7.prototype;g.h.zM=function(){this.cd=Math.min(3E5,2*this.cd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.cd+15E3*Math.random();g.$m(this.o,a);this.u=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.cd=5E3};g.Qa(c7,Ita);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.bf=function(a){return this.w.sh(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.qb||(this.qb=!0,g.je(this.w),Mta(this),g.je(this.u),this.u=null)};
g.h.ka=function(){return this.qb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.M+"/test";b=this.M+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.o;e&&(e.Yc=null);d.Yc=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Mi):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Cta(this.o,c)};
g.h.Av=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Cta(this.o,a[b])}this.R("handlerOpened")};
g.h.yv=function(a){var b=2==a&&401==this.o.Te;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.Np=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.hw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.dc(a,this.B);return a};
g.h.zv=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Ata(this.o)):this.R("handlerMessage",new Kta(a[0],a[1]))};
g.h.DN=function(){this.u.isActive();var a=this.o,b=0;a.Wb&&b++;a.wd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Uta=(0,g.H)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Qa(m7,g.Q);m7.prototype.Td=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ha)&&this.aC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ha)||(g.No(this.Ha),this.Ha=NaN)};
g.h.X=function(){this.stop();g.Q.prototype.X.call(this)};
g.h.aC=function(){this.Ha=NaN;this.o=g.Lp(f7(this.C,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.EO,this),onError:(0,g.x)(this.DO,this),Zd:(0,g.x)(this.FO,this)})};
g.h.EO=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.w;c.name=this.A;this.R("pairingComplete",new e6(c))};
g.h.DO=function(a){this.o=null;a.status&&404==a.status?this.u>=cva.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=cva[this.u],this.Ha=g.Lo((0,g.x)(this.aC,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.FO=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var cva=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.Es("yt-remote-lounge-token-expiration")&&Yta(this);g.No(this.u);this.u=g.Lo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Vta(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||Yta(this)};
g.h.remove=function(a,b){var c=o7(this);Xta(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Lo=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.X=function(){g.No(this.u);p7.Cb.X.call(this)};
g.h.vE=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.uE=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Es("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?u7(this):(this.A=(0,g.H)()+3E5,g.Ds("yt-remote-fast-check-period",this.A),this.it())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.No(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.X.call(this)};
g.h.it=function(){g.No(this.w);this.w=NaN;this.u&&this.u.abort();var a=aua(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.eM,this,a),(0,g.x)(this.dM,this))}else t7(this,{}),u7(this)};
g.h.eM=function(a,b){this.u=null;var c=g.Sb(aua(this));if(g.rb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Ob("Changing Screen set during request."),this.it()};
g.h.dM=function(a){this.Ob("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Ob=function(a){i7("OnlineScreenService",a)};g.Qa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Lo=function(a,b,c,d){this.w.contains(a)?this.w.Lo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.Td=function(a){return a?this.o:g.fb(this.o,(0,g.Yd)(this.A,function(b){return!this.contains(b)},this))};
g.h.bC=function(){return(0,g.Yd)(this.Td(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.cC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.je(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.je(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.HO=function(a,b,c,d){g.Lp(f7(this.C,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||eua(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);eua(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Zd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.je(this.w);g.je(this.u);v7.Cb.X.call(this)};
g.h.DE=function(){fua(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Qa(y7,g.Q);g.h=y7.prototype;g.h.fo=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.Yd=function(a){this.ka()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.O,a)};
g.h.eC=function(){return null};
g.h.wt=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.wt("");y7.Cb.X.call(this)};g.Qa(A7,y7);g.h=A7.prototype;g.h.vt=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);hua(this)};
g.h.Ni=function(a){this.info("launchWithParams no-op for Cast: "+g.Nk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Yd()},this),(0,g.x)(function(){this.Yd(Error("Failed to stop receiver app."))},this)):this.Yd(Error("Stopping cast device witout session."))};
g.h.wt=g.Fa;g.h.X=function(){this.info("disposeInternal");g.No(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Cb.X.call(this)};
g.h.ZM=function(a,b){if(!this.ka())if(b){var c=x6(b);if(g.La(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Nk(c));switch(d){case "mdxSessionStatus":gua(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Cw=function(a,b,c,d){dua(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Lo((0,g.x)(this.Cw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.eC=function(){return this.o};
g.h.IO=function(a){this.ka()||a||(z7(this,"Cast session died."),this.Yd())};g.Qa(B7,y7);g.h=B7.prototype;g.h.vt=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.Ni=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Fa;g.No(this.C);this.A?this.A.stop((0,g.x)(this.Yd,this,null),(0,g.x)(this.Yd,this,"Failed to stop DIAL device.")):this.Yd()};
g.h.X=function(){this.o();this.o=g.Fa;g.No(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;B7.Cb.X.call(this)};
g.h.LO=function(a){this.ka()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Fa,this.Yd())};
g.h.Rq=function(a){this.M=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,jua(this));a(b);iua(this)}else this.F=(0,g.x)(function(){g.No(this.C);this.F=g.Fa;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,jua(this));a(c);iua(this)},this),this.C=g.Lo((0,g.x)(function(){this.F()},this),100)};
g.h.WE=function(a,b,c){dua(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.fo(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Rq(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Rq(b,c)},this))};g.Qa(C7,y7);C7.prototype.stop=function(){this.Yd()};
C7.prototype.vt=g.Fa;C7.prototype.Ni=function(){g.No(this.o);this.o=NaN;var a=k6(this.H.Td(),this.u.label);a?this.fo(a):this.Yd(Error("No such screen"))};
C7.prototype.X=function(){g.No(this.o);this.o=NaN;C7.Cb.X.call(this)};g.Qa(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.NL,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.Wz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.dK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ka()||
(chrome.cast.addReceiverActionListener(this.A),Rta(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.dC,this)),this.w=lua(this),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(k){this.Ob("Failed to set initial custom receivers: "+g.Nk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Ob("Failed to initialize API: "+g.Nk(k));
b(!1)},this))};
g.h.KN=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.Td(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=kua(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Fa,(0,g.x)(function(e){this.Ob("Failed to set initial custom receivers: "+g.Nk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.wt(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.LN=function(a){this.ka()?this.Ob("Setting connection data on disposed cast v2"):this.o?this.o.Ni(a):this.Ob("Setting connection data without a session")};
g.h.KO=function(){this.ka()?this.Ob("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.Wz,this),(0,g.x)(this.iM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.dC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Ota,b=g.w("yt.mdx.remote.debug.handlers_");g.cb(b||[],a);g.je(this.o);D7.Cb.X.call(this)};
g.h.Ob=function(a){i7("Controller",a)};
g.h.Xz=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.JL=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Ob("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Ob("Stopping receiver w/o session: "+a.friendlyName)}else this.Ob("onReceiverAction_ called without receiver.")};
g.h.dK=function(a){if(this.ka())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Ob("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Ob("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Ob('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.WE,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Rq,b))};
g.h.Wz=function(a){if(!this.ka()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Ob("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.Td(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.je(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.Xz,this,this.o)),this.o.Ni(null));this.o.vt(a)}}};
g.h.JO=function(){return this.o?this.o.eC():null};
g.h.iM=function(a){this.ka()||(this.Ob("Failed to estabilish a session: "+g.Nk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.NL=function(a){E7("Receiver availability updated: "+a);if(!this.ka()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.dC=function(){this.ka()||(this.w=lua(this),E7("Updating custom receivers: "+g.Nk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Fa,(0,g.x)(function(){this.Ob("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.LN;D7.prototype.setConnectedScreenStatus=D7.prototype.KN;D7.prototype.stopSession=D7.prototype.KO;D7.prototype.getCastSession=D7.prototype.JO;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Ue=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Fa,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Fa,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Fa,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Oa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Fa,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Ob("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Ob("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Oa(this.setVolume,a,b))};
g.h.XA=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Nk(b.style),g.dc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Oa(this.XA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Oa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Nk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.ZB=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Oa(this.ZB,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Oa(this.nextVideo,a,b))};
g.h.Lv=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Lv)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.X=function(){yua(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.X.call(this)};
g.h.cu=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.$a(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.GL=function(a,b){this.R(a,b)};
g.h.KJ=function(a){if(!a)this.Uk(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.Uk=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),zua(this),this.R("remotePlayerChange")};
g.h.JJ=function(a){a?(zua(this),this.R("remotePlayerChange")):this.Uk(null)};
g.h.WJ=function(){var a=vua();a&&Y7(this,a)};
g.h.Ob=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;U7(this.Sa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Nk(l));this.o.connect({method:"setPlaylist",
params:g.Nk(l)},a,Msa())}else g8("Connecting without params"),this.o.connect({},a,Msa());Bua(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.No(this.F);this.F=NaN;g.No(this.G);this.G=NaN;this.w=null;g.Uq(this.O);this.O.length=0;this.o.dispose();g.Q.prototype.X.call(this);this.A=this.C=this.u=this.Sa=this.o=null};
g.h.oE=function(){this.ni(2)};
g.h.OJ=function(){g8("Channel opened");this.J&&(this.J=!1,j8(this),this.M=g.Lo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.ni(1)},this),15E3));
Qsa(Lta(this.o),this.T)};
g.h.LJ=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.MJ=function(a){q6();isNaN(this.Zj())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.J=!0,g8("Channel error: "+a+" with reconnection in "+this.Zj()+" ms"),h8(this,2))};
g.h.NJ=function(a){a.params?g8("Received: action="+a.action+", params="+g.Nk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Ic)(a,function(c){return new d6(c)});
a=!!g.Va(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Eua(this,a);break;case "loungeScreenDisconnected":g.db(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Eua(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Va(this.u,function(c){return b?c.id==b.id:!1})||wsa(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.db(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Gua(this,a);break;case "nowPlaying":Iua(this,a);break;case "onStateChange":Hua(this,a);break;case "onAdStateChange":Jua(this,a);break;case "onVolumeChanged":Kua(this,a);break;case "onSubtitlesTrackChanged":Fua(this,a);break;case "nowAutoplaying":Lua(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":Mua(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.zN=function(){if(this.w){var a=this.w;this.w=null;this.Sa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.dE=function(){var a=3;this.ka()||(a=0,isNaN(this.Zj())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.ni=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&q6();Mta(this.o,a);this.dispose()};
g.h.cE=function(){var a=this.Sa;this.w&&(a=this.Sa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.MN=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.w=b.videoId,g.No(this.F),this.F=g.Lo((0,g.x)(this.zN,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&V7(this.Sa)==V7(b)&&g.Nk(this.Sa.o)==g.Nk(b.o)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.z)(c,function(d){this.R(d)},this)};
g.h.Aw=function(){var a=this.o.C.id,b=g.Va(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Zj=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.H)():NaN};
g.h.RD=function(){return this.A||"UNSUPPORTED"};
g.h.SD=function(){return this.C||""};
g.h.CO=function(){if(!isNaN(this.Zj())){var a=this.o.u;g.an(a.o);a.start()}};
g.h.HN=function(a,b){l8(this,a,b);Dua(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.bf;f8.prototype.getProxyState=f8.prototype.dE;f8.prototype.disconnect=f8.prototype.ni;f8.prototype.getPlayerContextData=f8.prototype.cE;f8.prototype.setPlayerContextData=f8.prototype.MN;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Aw;f8.prototype.getReconnectTimeout=f8.prototype.Zj;f8.prototype.getAutoplayMode=f8.prototype.RD;f8.prototype.getAutoplayVideoId=f8.prototype.SD;f8.prototype.reconnect=f8.prototype.CO;
f8.prototype.sendMessage=f8.prototype.HN;g.r(m8,m7);g.h=m8.prototype;g.h.Td=function(a){return this.bd.$_gs(a)};
g.h.contains=function(a){return!!this.bd.$_c(a)};
g.h.get=function(a){return this.bd.$_g(a)};
g.h.start=function(){this.bd.$_st()};
g.h.add=function(a,b,c){this.bd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.bd.$_r(a,b,c)};
g.h.Lo=function(a,b,c,d){this.bd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.bd.$_ubk(this.u[a]);this.u.length=0;this.bd=null;m7.prototype.X.call(this)};
g.h.GO=function(){this.R("screenChange")};
g.h.lL=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.HO;v7.prototype.$_gsppc=v7.prototype.cC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Lo;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Td;v7.prototype.$_gos=v7.prototype.bC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.bf;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.X=function(){g.A.prototype.X.call(this);this.A.stop();this.C.stop();this.J.stop();this.U();this.o.unsubscribe("proxyStateChange",this.Tz,this);this.o.unsubscribe("remotePlayerChange",this.Xk,this);this.o.unsubscribe("remoteQueueChange",this.ho,this);this.o.unsubscribe("autoplayUpNext",this.vz,this);this.o.unsubscribe("previousNextChange",this.Qz,this);this.o.unsubscribe("nowAutoplaying",this.Mz,this);this.o.unsubscribe("autoplayDismissed",this.uz,this);this.o=this.B=null};
g.h.sy=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.M.Jw(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.IJ=function(a){this.J.kE(a)};
g.h.iO=function(a){this.sy("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.mB=function(){var a=this.u.getOption("captions","track");g.Yb(a)||K8(this,a)};
g.h.Fz=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.Xk,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.O.start();this.o.subscribe("remotePlayerChange",this.Xk,this)}};
g.h.HK=function(){g.Yb(this.F)||Yua(this,this.F);this.G=!1};
g.h.Tz=function(a,b){this.C.stop();2==b&&this.jB()};
g.h.Xk=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.wD(8));this.iB();break;case 1085:case 3:I8(this,new g.wD(9));break;case 1083:case 0:I8(this,new g.wD(2));this.M.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.wD(4));break;case 2:I8(this,new g.wD(4));H8(this,V7(a));
break;case -1:I8(this,new g.wD(64));break;case -1E3:I8(this,new g.wD(128,{errorCode:"mdx.remoteerror",errorMessage:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.F=a,Yua(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.O.isActive()||this.OB()}else Xua(this)};
g.h.Qz=function(){this.u.R("mdxpreviousnextchange")};
g.h.ho=function(){J8(this)||Xua(this)};
g.h.gD=function(){this.o.Lv()};
g.h.vz=function(){};
g.h.Mz=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.uz=function(){this.u.R("mdxautoplaycanceled")};
g.h.jH=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.OB=function(){if(J8(this)){var a=$7(this.o);this.w.Va(this.T);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.T=this.w.L(this.u,"onVolumeChange",this.Fz)}};
g.h.iB=function(){this.A.stop();if(!this.o.ka()){var a=$7(this.o);1==a.playerState&&I8(this,new g.wD(8));H8(this,V7(a));this.A.start()}};
g.h.jB=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.V);M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.V);N8.prototype.A=function(a){$ua(this,a.state)};g.r(O8,g.qO);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.tb(a,this.B,this),g.sO(this,(0,g.Ic)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.oe(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.Ee=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.C[a].name};
O8.prototype.Uc=function(a){g.qO.prototype.Uc.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.ib()};g.r(P8,g.zP);g.h=P8.prototype;
g.h.create=function(){Rua(g.Kx(this.player.P()));this.A.push(g.So("yt-remote-before-disconnect",this.FJ,this));this.A.push(g.So("yt-remote-connection-change",this.OL,this));this.A.push(g.So("yt-remote-receiver-availability-change",this.Rz,this));this.A.push(g.So("yt-remote-auto-connect",this.ML,this));this.A.push(g.So("yt-remote-receiver-resumed",this.LL,this));this.A.push(g.So("mdx-privacy-popup-confirm",this.nN,this));this.A.push(g.So("mdx-privacy-popup-cancel",this.mN,this));this.Rz()};
g.h.load=function(){this.player.cancelPlayback();g.zP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Wua())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.O=a||0,this.player.R("progresssync",a,void 0));Zua(this,this.F,this.F);g.US(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.ke(this.B,this.o);this.o=this.B=null;g.zP.prototype.unload.call(this);g.US(this.player.app,5);Q8(this)};
g.h.X=function(){g.To(this.A);g.zP.prototype.X.call(this)};
g.h.Hk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.sy.apply(this.B,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.H};
g.h.fE=function(){return this.loaded?this.B.suggestion:null};
g.h.Ue=function(){return this.o?$7(this.o).Ue:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.O};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.P().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.yc():!a.isAdPlaying()&&this.player.yc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.LG=function(){this.o&&this.o.ZB()};
g.h.FJ=function(a){1==a&&(this.T=this.o?$7(this.o):null)};
g.h.OL=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.T=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.je(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.T)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Rz=function(){this.M=[this.u].concat(Tua());var a=y8()||this.u;R8(this,a);this.player.la("onMdxReceiversChange")};
g.h.eN=function(a){!this.J&&g.KD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.ML=function(){var a=y8();R8(this,a)};
g.h.LL=function(){this.w=y8()};
g.h.nN=function(){this.J=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.mN=function(){this.J=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Ec=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.M;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.M.length&&"cast-selector-receiver"==this.M[1].key?(b&&P7(),!0):!1}};
g.h.MG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.lf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.OP.remote=P8;})(_yt_player);
